src/FakeFilter.UI/Controllers/ListController.cs
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using FakeFilter.UI.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FakeFilter.UI.Controllers
{
	public class ListController : Controller
	{
		private readonly ServerDbContext dbContext;

		public ListController(ServerDbContext dbContext)
		{
			this.dbContext = dbContext;
		}

		public async Task<IActionResult> Index()
		{
			ViewData["Title"] = "Domainlist";

			var mapping = await dbContext.HostProviderMappings
				.Include(m => m.Host)
				.Include(m => m.Provider)
				.GroupBy(m => m.Host.Name)
				.Select(grouping => new
				{
					Host = grouping.Key,
					Providers = grouping.Select(g => g.Provider.Name).ToArray()
				})
				.ToDictionaryAsync(
					a => a.Host,
					a => a.Providers,
					HttpContext.RequestAborted
				);

			return View(mapping);
		}
	}
}

src/FakeFilter.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>FakeFilter UI - @ViewBag.Title</title>

		<link rel="apple-touch-icon" sizes="57x57" href="~/ico/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="~/ico/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="~/ico/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="~/ico/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="~/ico/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="~/ico/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="~/ico/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="~/ico/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="~/ico/apple-icon-180x180.png">
		
		<link rel="icon" type="image/png" sizes="192x192" href="~/ico/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="~/ico/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="~/ico/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="~/ico/favicon-16x16.png">

		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	</head>

	<body class="h-100">
		<main class="w-100 h-100 container mx-auto d-flex flex-column">
			<div class="mb-auto"></div>
			<div class="px-3">
				@RenderBody()
			</div>
			<div class="mt-auto"></div>
		</main>

		<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
			<div class="container">
				<a asp-controller="Home" asp-action="Index" asp-route-id="" class="navbar-brand">FakeFilter UI</a>
				<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#main-navigation" aria-controls="main-navigation" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="main-navigation">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a asp-controller="Home" asp-action="Index" asp-route-id="" class="nav-link"><span class="fa-solid fa-fw fa-search"></span> Search</a>
						</li>
						<li class="nav-item">
							<a asp-controller="List" asp-action="Index" asp-route-id="" class="nav-link"><span class="fa-solid fa-fw fa-list"></span> Domainlist</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Changelog" asp-action="Index" asp-route-id="" class="nav-link"><span class="fa-solid fa-fw fa-scroll"></span> Changelog</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
		<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
		@RenderSection("Scripts", required: false)
	</body>
</html>